<?php
namespace GodsDev\Backyard;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-06-24 at 22:21:10.
 */
class BackyardArrayTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var BackyardArray
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new BackyardArray(new BackyardError);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers GodsDev\Backyard\BackyardArray::inArrayWildcards
     * @todo   Implement testInArrayWildcards().
     */
    public function testInArrayWildcards()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers GodsDev\Backyard\BackyardArray::getOneColumnFromArray
     * @todo   Implement testGetOneColumnFromArray().
     */
    public function testGetOneColumnFromArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers GodsDev\Backyard\BackyardArray::removeOneColumnFromArray
     * @todo   Implement testRemoveOneColumnFromArray().
     */
    public function testRemoveOneColumnFromArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers GodsDev\Backyard\BackyardArray::dumpArrayAsOneLine
     * @todo   Implement testDumpArrayAsOneLine().
     */
    public function testDumpArrayAsOneLine()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers GodsDev\Backyard\BackyardArray::arrayVlookup
     * @todo   Implement testArrayVlookup().
     */
    public function testArrayVlookup()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers GodsDev\Backyard\BackyardArray::array_diff_assoc_recursive
     * @todo   Implement testArray_diff_assoc_recursive().
     */
    public function testArray_diff_assoc_recursive()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
