<?php
namespace GodsDev\Backyard;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-06-24 at 22:21:10.
 */
class BackyardJsonTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var BackyardJson
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new BackyardJson(new BackyardError);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers GodsDev\Backyard\BackyardJson::minifyJSON
     * @todo   Implement testMinifyJSON().
     */
    public function testMinifyJSON()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers GodsDev\Backyard\BackyardJson::outputJSON
     * @todo   Implement testOutputJSON().
     */
    public function testOutputJSON()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers GodsDev\Backyard\BackyardJson::jsonCleanDecode
     * @todo   Implement testJsonCleanDecode().
     */
    public function testJsonCleanDecode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers GodsDev\Backyard\BackyardJson::getJsonAsArray
     * @todo   Implement testGetJsonAsArray().
     */
    public function testGetJsonAsArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
