<?php
namespace GodsDev\Backyard;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-06-24 at 22:21:11.
 */
class BackyardHttpTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var BackyardHttp
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new BackyardHttp(new BackyardError);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers GodsDev\Backyard\BackyardHttp::movePage
     * @todo   Implement testMovePage().
     */
    public function testMovePage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers GodsDev\Backyard\BackyardHttp::retrieveFromPostThenGet
     * @todo   Implement testRetrieveFromPostThenGet().
     */
    public function testRetrieveFromPostThenGet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers GodsDev\Backyard\BackyardHttp::getCurPageURL
     * @todo   Implement testGetCurPageURL().
     */
    public function testGetCurPageURL()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers GodsDev\Backyard\BackyardHttp::getData
     * @todo   Implement testGetData().
     */
    public function testGetData()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers GodsDev\Backyard\BackyardHttp::getHTTPstatusCode
     * @todo   Implement testGetHTTPstatusCode().
     */
    public function testGetHTTPstatusCode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers GodsDev\Backyard\BackyardHttp::getHTTPstatusCodeByUA
     * @todo   Implement testGetHTTPstatusCodeByUA().
     */
    public function testGetHTTPstatusCodeByUA()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
