<?php
namespace GodsDev\Backyard;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-06-24 at 22:21:09.
 */
class BackyardTimeTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var BackyardTime
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new BackyardTime(new BackyardError);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers GodsDev\Backyard\BackyardTime::getmicrotime
     * @todo   Implement testGetmicrotime().
     */
    public function testGetmicrotime()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers GodsDev\Backyard\BackyardTime::getRunningTime
     * @todo   Implement testGetRunningTime().
     */
    public function testGetRunningTime()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers GodsDev\Backyard\BackyardTime::pageGeneratedIn
     * @todo   Implement testPageGeneratedIn().
     */
    public function testPageGeneratedIn()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
