<?php

/**
 * @todo how to test this?
 */

//namespace WorkOfStan\Backyard;
//
///**
// * Generated by PHPUnit_SkeletonGenerator on 2016-06-25 at 17:57:37.
// */
//class BackyardErrorTest extends \PHPUnit_Framework_TestCase
//{
//    /**
//     * @var BackyardError
//     */
//    protected $object;
//
//    /**
//     * Sets up the fixture, for example, opens a network connection.
//     * This method is called before a test is executed.
//     */
//    protected function setUp()
//    {
//        $this->object = new BackyardError;
//    }
//
//    /**
//     * Tears down the fixture, for example, closes a network connection.
//     * This method is called after a test is executed.
//     */
//    protected function tearDown()
//    {
//    }
//
//    /**
//     * @covers WorkOfStan\Backyard\BackyardError::log
//     * @todo   Implement testLog().
//     */
//    public function testLog()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//            'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers WorkOfStan\Backyard\BackyardError::dieGraciously
//     * @todo   Implement testDieGraciously().
//     */
//    public function testDieGraciously()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//            'This test has not been implemented yet.'
//        );
//    }
//}
