<?php
namespace GodsDev\Backyard;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-06-24 at 22:21:11.
 */
class BackyardCryptTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var BackyardCrypt
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new BackyardCrypt(new BackyardError);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers GodsDev\Backyard\BackyardCrypt::randomId
     * @todo   Implement testRandomId().
     */
    public function testRandomId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
