<?php

namespace GodsDev\Backyard\Test;

use GodsDev\Backyard\BackyardCrypt;
use GodsDev\Backyard\BackyardError;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-06-25 at 17:57:39.
 */
class BackyardCryptTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var BackyardCrypt
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        error_reporting(E_ALL); // incl E_NOTICE
        $this->object = new BackyardCrypt(new BackyardError(array('logging_level' => 4)));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        // no action
    }

    /**
     * @covers GodsDev\Backyard\BackyardCrypt::randomId
     */
    public function testRandomId()
    {
        $orig = $this->object->randomId();
        $expected = $this->object->randomId();

        $this->assertNotEquals($expected, $orig);
    }

    /**
     * @covers GodsDev\Backyard\BackyardCrypt::randomId
     */
    public function testRandomIdDefault10()
    {
        $orig = $this->object->randomId();
        $expected = 10;

        $this->assertEquals($expected, strlen($orig));
    }

    /**
     * @covers GodsDev\Backyard\BackyardCrypt::randomId
     */
    public function testRandomIdLength32()
    {
        $orig = $this->object->randomId(32);
        $expected = 32;

        $this->assertEquals($expected, strlen($orig));
    }

    /**
     * @covers GodsDev\Backyard\BackyardCrypt::randomId
     */
    public function testRandomIdLength1024()
    {
        $orig = $this->object->randomId(1024);
        $expected = 1024;
        //error_log($orig);
        $this->assertEquals($expected, strlen($orig));
    }
}
