<?php
//@todo - make the tests
//
//namespace GodsDev\Backyard\Test;
//
//use GodsDev\Backyard\BackyardGeo;
//use GodsDev\Backyard\BackyardError;
//
////@todo - put into separate group as it needs access both to database and internet
//
///**
// * Generated by PHPUnit_SkeletonGenerator on 2016-06-25 at 17:57:38.
// */
//class BackyardGeoTest extends \PHPUnit_Framework_TestCase
//{
//    /**
//     * @var BackyardGeo
//     */
//    protected $object;
//
//    /**
//     * Sets up the fixture, for example, opens a network connection.
//     * This method is called before a test is executed.
//     */
//    protected function setUp()
//    {
//        $this->object = new BackyardGeo(new BackyardError);
//    }
//
//    /**
//     * Tears down the fixture, for example, closes a network connection.
//     * This method is called after a test is executed.
//     */
//    protected function tearDown()
//    {
//    }
//
//    /**
//     * @covers GodsDev\Backyard\BackyardGeo::getClosestPOI
//     * @todo   Implement testGetClosestPOI().
//     */
//    public function testGetClosestPOI()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//            'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers GodsDev\Backyard\BackyardGeo::getListOfPOI
//     * @todo   Implement testGetListOfPOI().
//     */
//    public function testGetListOfPOI()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//            'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers GodsDev\Backyard\BackyardGeo::calculateDistanceFromLatLong
//     * @todo   Implement testCalculateDistanceFromLatLong().
//     */
//    public function testCalculateDistanceFromLatLong()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//            'This test has not been implemented yet.'
//        );
//    }
//}
