<?php

/**
 * @todo make database call testable
 */

//namespace WorkOfStan\Backyard\Tests;
//
//use WorkOfStan\Backyard\BackyardMysqli;
//use WorkOfStan\Backyard\BackyardError;
//
//
///**
// * Generated by PHPUnit_SkeletonGenerator on 2016-06-25 at 17:57:38.
// */
//class BackyardMysqliTest extends \PHPUnit_Framework_TestCase
//{
//    /**
//     * @var BackyardMysqli
//     */
//    protected $object;
//
//    /**
//     * Sets up the fixture, for example, opens a network connection.
//     * This method is called before a test is executed.
//     */
//    protected function setUp()
//    {
//        $this->object = new BackyardMysqli(new BackyardError);
//    }
//
//    /**
//     * Tears down the fixture, for example, closes a network connection.
//     * This method is called after a test is executed.
//     */
//    protected function tearDown()
//    {
//    }
//
//    /**
//     * @covers WorkOfStan\Backyard\BackyardMysqli::query
//     * @todo   Implement testQuery().
//     */
//    public function testQuery()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//            'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers WorkOfStan\Backyard\BackyardMysqli::queryArray
//     * @todo   Implement testQueryArray().
//     */
//    public function testQueryArray()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//            'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers WorkOfStan\Backyard\BackyardMysqli::nextIncrement
//     * @todo   Implement testNextIncrement().
//     */
//    public function testNextIncrement()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//            'This test has not been implemented yet.'
//        );
//    }
//}
