<?php
namespace GodsDev\Backyard\Test;
use GodsDev\Backyard\Backyard;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-06-25 at 18:53:30.
 */
class BackyardTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Backyard
     */
    protected $object;
    
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Backyard(array('logging_level' => 4));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
    
    public function testBackyardJsonMinifyJson() {
        //$this->Backyard = new \GodsDev\Backyard\Backyard(array());
        $orig = '{"status": "1230", "text": "abc"}';
        $expected = '{"status":"1230","text":"abc"}';
        
        $this->assertEquals($expected, $this->object->Json->minifyJSON($orig));
    }
    
}
