###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: Lint Code Base

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  push:
    branches-ignore:
      # notest branches to ignore testing of partial online commits
      - 'notest/**'
  pull_request:
    branches-ignore:
      # notest branches to ignore testing of partial online commits
      - 'notest/**'

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest
    # Limit the running time
    timeout-minutes: 10

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2

      # composer to provide context for PHPStan
      #- name: Install dependencies
      #  run: "composer update --prefer-dist --no-progress --ignore-platform-req=php"

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter@main
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.yml
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_ANSIBLE: false
          VALIDATE_HTML: false
          VALIDATE_JSCPD: false
          # PHPStan run in matrix strategy in php-composer-phpunit.yml
          VALIDATE_PHP_PHPSTAN: false
          VALIDATE_PHP_PSALM: false
