name: PHP Composer + PHPUnit + PHPStan

on:
  push:
    branches-ignore:
      # notest branches to ignore testing of partial online commits
      - 'notest/**'

  pull_request:
    branches-ignore:
      # notest branches to ignore testing of partial online commits
      - 'notest/**'

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}
    # Limit the running time
    timeout-minutes: 10
    strategy:
      matrix:
        operating-system:
          - "ubuntu-latest"
        php-version: ['5.3', '5.6', '7.3', '7.4']

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: "Install PHP ${{ matrix.php-version }} Test on ${{ matrix.operating-system }}"
      uses: "shivammathur/setup-php@v2"
      with:
        php-version: "${{ matrix.php-version }}"
        tools: composer:v2, phpstan
        # Note: phpstan call fails for PHP<7.1
        # tools: composer:v2, phpunit
      env:
        # fixes Error: Could not authenticate against github.com
        COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # https://github.com/actions/cache
    # A repository can have up to 5GB of caches. Once the 5GB limit is reached, older caches will be evicted based on when the cache was last accessed.
    # Caches that are not accessed within the last week will also be evicted.
    - name: Cache composer dependencies
      uses: actions/cache@v2
      id: vendor-cache
      with:
        # path to Checkout working directory is /home/runner/work/repo-name/repo-name , so just add /vendor/
        path: ${{ github.workspace }}/vendor/
        # Use composer.json for key, if composer.lock is not committed.
        key: ${{ runner.os }}-PHP${{ matrix.php-version }}-vendor-${{ hashFiles('**/composer.json') }}
        # key: ${{ runner.os }}-PHP${{ matrix.php-version }}-vendor-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-PHP${{ matrix.php-version }}-vendor-

    - name: Validate composer.json and composer.lock
      if: ${{ steps.vendor-cache.outputs.cache-hit != 'true' }}
      run: composer validate

    - name: Install no-dev dependencies
      if: ${{ steps.vendor-cache.outputs.cache-hit != 'true' }}
      run: composer update --no-dev --prefer-dist --no-progress

    - name: Install dependencies
      if: ${{ steps.vendor-cache.outputs.cache-hit != 'true' }}
      run: composer update --prefer-dist --no-progress

    - name: "PHPUnit tests"
      run: "vendor/bin/phpunit"
    #- name: PHPUnit (php-actions)
    #  uses: php-actions/phpunit@v5
    #  with:
    #    # PHP included in ubuntu-latest does not support iconv //TRANSLIT flag as iconv implementation is unknown
    #    # https://github.com/actions/virtual-environments/blob/ubuntu18/20201026.1/images/linux/Ubuntu1804-README.md
    #    # therefore PHPUnit group iconvtranslit should be excluded
    #    configuration: phpunit.xml

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test

    # PHPStan works for PHP/7.1+ so it can't even be in composer.json
    - name: "PHPStan"
      #if: ${{ matrix.php-version >= '7.1' && steps.vendor-cache.outputs.cache-hit != 'true' }}
      #if: ${{ matrix.php-version != '5.3' && matrix.php-version != '5.6' }}
      # alternative syntax # if: ${{ matrix.php-version >= '7.1' }}
      #run: |
        #composer require --dev phpstan/phpstan:^0.12
        #vendor/bin/phpstan analyse --no-interaction --no-progress .
        # If removal needed:
        # composer remove --dev phpstan/phpstan
      if: ${{ matrix.php-version >= '7.1' }}
      run: phpstan --configuration=phpstan.neon.dist analyse --no-interaction --no-progress .
